//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class alipay_config
    {
        public long id { get; set; }
        public string app_id { get; set; }
        public string charset { get; set; }
        public string format { get; set; }
        public string gateway_url { get; set; }
        public string notify_url { get; set; }
        public string private_key { get; set; }
        public string public_key { get; set; }
        public string return_url { get; set; }
        public string sign_type { get; set; }
        public string sys_service_provider_id { get; set; }
    }
}
