//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class article
    {
        public long id { get; set; }
        public string cid { get; set; }
        public string title { get; set; }
        public string author { get; set; }
        public string image_input { get; set; }
        public string synopsis { get; set; }
        public string content { get; set; }
        public string share_title { get; set; }
        public string share_synopsis { get; set; }
        public string visit { get; set; }
        public Nullable<long> sort { get; set; }
        public string url { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public Nullable<bool> is_del { get; set; }
        public Nullable<bool> hide { get; set; }
        public Nullable<long> admin_id { get; set; }
        public Nullable<long> mer_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<bool> is_hot { get; set; }
        public Nullable<bool> is_banner { get; set; }
    }
}
