//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class column_config
    {
        public long id { get; set; }
        public string table_name { get; set; }
        public string column_name { get; set; }
        public string column_type { get; set; }
        public string dict_name { get; set; }
        public string extra { get; set; }
        public Nullable<bool> form_show { get; set; }
        public string form_type { get; set; }
        public string key_type { get; set; }
        public Nullable<bool> list_show { get; set; }
        public Nullable<bool> not_null { get; set; }
        public string query_type { get; set; }
        public string remark { get; set; }
        public string date_annotation { get; set; }
    }
}
