//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class email_config
    {
        public long id { get; set; }
        public string from_user { get; set; }
        public string host { get; set; }
        public string pass { get; set; }
        public string port { get; set; }
        public string user { get; set; }
    }
}
