//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using Interceptor;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure.Interception;

    public partial class eshoppingEntities : DbContext
    {
        public eshoppingEntities()
            : base("name=eshoppingEntities")
        {
            DbInterception.Add(new EFCommandInterceptor());
                //全局关闭懒加载;
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //不映射到数据库中
           // modelBuilder.Entity<store_cart>().Ignore(p => p.store_product_attr_value);
        }
    
        public virtual DbSet<article> articles { get; set; }
        public virtual DbSet<column_config> column_config { get; set; }
        public virtual DbSet<dict> dicts { get; set; }
        public virtual DbSet<dict_detail> dict_detail { get; set; }
        public virtual DbSet<eshop_user> eshop_user { get; set; }
        public virtual DbSet<express> expresses { get; set; }
        public virtual DbSet<gen_config> gen_config { get; set; }
        public virtual DbSet<gen_test> gen_test { get; set; }
        public virtual DbSet<local_storage> local_storage { get; set; }
        public virtual DbSet<log> logs { get; set; }
        public virtual DbSet<material> materials { get; set; }
        public virtual DbSet<material_group> material_group { get; set; }
        public virtual DbSet<menu> menus { get; set; }
        public virtual DbSet<picture> pictures { get; set; }
        public virtual DbSet<quartz_job> quartz_job { get; set; }
        public virtual DbSet<quartz_log> quartz_log { get; set; }
        public virtual DbSet<store_cart> store_cart { get; set; }
        public virtual DbSet<store_category> store_category { get; set; }
        public virtual DbSet<store_coupon> store_coupon { get; set; }
        public virtual DbSet<store_coupon_issue> store_coupon_issue { get; set; }
        public virtual DbSet<store_coupon_issue_user> store_coupon_issue_user { get; set; }
        public virtual DbSet<store_coupon_user> store_coupon_user { get; set; }
        public virtual DbSet<store_customer> store_customer { get; set; }
        public virtual DbSet<store_order> store_order { get; set; }
        public virtual DbSet<store_order_cart_info> store_order_cart_info { get; set; }
        public virtual DbSet<store_order_status> store_order_status { get; set; }
        public virtual DbSet<store_product> store_product { get; set; }
        public virtual DbSet<store_product_attr> store_product_attr { get; set; }
        public virtual DbSet<store_product_attr_result> store_product_attr_result { get; set; }
        public virtual DbSet<store_product_attr_value> store_product_attr_value { get; set; }
        public virtual DbSet<store_product_relation> store_product_relation { get; set; }
        public virtual DbSet<store_product_reply> store_product_reply { get; set; }
        public virtual DbSet<store_product_rule> store_product_rule { get; set; }
        public virtual DbSet<store_seckill> store_seckill { get; set; }
        public virtual DbSet<store_visit> store_visit { get; set; }
        public virtual DbSet<system_attachment> system_attachment { get; set; }
        public virtual DbSet<system_city> system_city { get; set; }
        public virtual DbSet<system_config> system_config { get; set; }
        public virtual DbSet<system_group_data> system_group_data { get; set; }
        public virtual DbSet<system_user_task> system_user_task { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<user_address> user_address { get; set; }
        public virtual DbSet<user_avatar> user_avatar { get; set; }
        public virtual DbSet<user_bill> user_bill { get; set; }
        public virtual DbSet<user_recharge> user_recharge { get; set; }
        public virtual DbSet<user_sign> user_sign { get; set; }
    }
}
