//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class eshop_user
    {
        public long uid { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string real_name { get; set; }
        public Nullable<int> birthday { get; set; }
        public string card_id { get; set; }
        public string mark { get; set; }
        public Nullable<int> partner_id { get; set; }
        public Nullable<int> group_id { get; set; }
        public string nickname { get; set; }
        public string avatar { get; set; }
        public string phone { get; set; }
        public string add_ip { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public string last_ip { get; set; }
        public decimal brokerage_price { get; set; }
        public int sign_num { get; set; }
        public bool status { get; set; }
        public byte level { get; set; }
        public Nullable<decimal> spread_uid { get; set; }
        public Nullable<System.DateTime> spread_time { get; set; }
        public string user_type { get; set; }
        public bool is_promoter { get; set; }
        public Nullable<long> pay_count { get; set; }
        public Nullable<int> spread_count { get; set; }
        public string addres { get; set; }
        public Nullable<long> adminid { get; set; }
        public string login_type { get; set; }
        public Nullable<bool> is_del { get; set; }
    }
}
