//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class gen_config
    {
        public long id { get; set; }
        public string table_name { get; set; }
        public string author { get; set; }
        public Nullable<bool> cover { get; set; }
        public string module_name { get; set; }
        public string pack { get; set; }
        public string path { get; set; }
        public string api_path { get; set; }
        public string prefix { get; set; }
        public string api_alias { get; set; }
    }
}
