//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public long id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string description { get; set; }
        public string exception_detail { get; set; }
        public string log_type { get; set; }
        public string method { get; set; }
        public string @params { get; set; }
        public string request_ip { get; set; }
        public Nullable<long> time { get; set; }
        public string username { get; set; }
        public string address { get; set; }
        public string browser { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<long> uid { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public Nullable<bool> is_del { get; set; }
    }
}
