//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class monitor_server
    {
        public int id { get; set; }
        public Nullable<int> cpu_core { get; set; }
        public Nullable<double> cpu_rate { get; set; }
        public Nullable<double> disk_total { get; set; }
        public Nullable<double> disk_used { get; set; }
        public Nullable<double> mem_total { get; set; }
        public Nullable<double> mem_used { get; set; }
        public string name { get; set; }
        public Nullable<int> port { get; set; }
        public Nullable<int> sort { get; set; }
        public string state { get; set; }
        public Nullable<double> swap_total { get; set; }
        public Nullable<double> swap_used { get; set; }
        public string address { get; set; }
    }
}
