//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class picture
    {
        public long id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string delete_url { get; set; }
        public string filename { get; set; }
        public string height { get; set; }
        public string size { get; set; }
        public string url { get; set; }
        public string username { get; set; }
        public string width { get; set; }
        public string md5code { get; set; }
    }
}
