//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class qiniu_content
    {
        public long id { get; set; }
        public string bucket { get; set; }
        public string name { get; set; }
        public string size { get; set; }
        public string type { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public string url { get; set; }
        public string suffix { get; set; }
    }
}
