//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class qiniu_config
    {
        public long id { get; set; }
        public string access_key { get; set; }
        public string bucket { get; set; }
        public string host { get; set; }
        public string secret_key { get; set; }
        public string type { get; set; }
        public string zone { get; set; }
    }
}
