//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class shipping_templates
    {
        public long id { get; set; }
        public string name { get; set; }
        public Nullable<bool> type { get; set; }
        public string region_info { get; set; }
        public Nullable<bool> appoint { get; set; }
        public string appoint_info { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public Nullable<bool> is_del { get; set; }
        public Nullable<int> sort { get; set; }
    }
}
