//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class shipping_templates_free
    {
        public int id { get; set; }
        public int province_id { get; set; }
        public int temp_id { get; set; }
        public int city_id { get; set; }
        public decimal number { get; set; }
        public decimal price { get; set; }
        public bool type { get; set; }
        public string uniqid { get; set; }
    }
}
