//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class store_product
    {
        public decimal id { get; set; }
        public Nullable<long> mer_id { get; set; }
        public string image { get; set; }
        public string slider_image { get; set; }
        public string store_name { get; set; }
        public string store_info { get; set; }
        public string keyword { get; set; }
        public string bar_code { get; set; }
        public string cate_id { get; set; }
        public decimal price { get; set; }
        public Nullable<decimal> vip_price { get; set; }
        public Nullable<decimal> ot_price { get; set; }
        public Nullable<decimal> postage { get; set; }
        public string unit_name { get; set; }
        public Nullable<short> sort { get; set; }
        public Nullable<int> sales { get; set; }
        public Nullable<int> stock { get; set; }
        public Nullable<bool> is_show { get; set; }
        public Nullable<bool> is_hot { get; set; }
        public Nullable<bool> is_benefit { get; set; }
        public Nullable<bool> is_best { get; set; }
        public Nullable<bool> is_new { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public Nullable<bool> is_postage { get; set; }
        public Nullable<bool> is_del { get; set; }
        public Nullable<bool> mer_use { get; set; }
        public Nullable<decimal> give_integral { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<bool> is_seckill { get; set; }
        public Nullable<bool> is_bargain { get; set; }
        public Nullable<bool> is_good { get; set; }
        public Nullable<int> ficti { get; set; }
        public Nullable<int> browse { get; set; }
        public string code_path { get; set; }
        public Nullable<bool> is_sub { get; set; }
        public Nullable<int> temp_id { get; set; }
        public Nullable<bool> spec_type { get; set; }
        public Nullable<bool> is_integral { get; set; }
        public Nullable<int> integral { get; set; }
    }
}
