//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class store_visit
    {
        public long id { get; set; }
        public Nullable<long> product_id { get; set; }
        public string product_type { get; set; }
        public Nullable<int> cate_id { get; set; }
        public string type { get; set; }
        public Nullable<long> uid { get; set; }
        public Nullable<int> count { get; set; }
        public string content { get; set; }
        public Nullable<int> add_time { get; set; }
    }
}
