//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class store_pink
    {
        public decimal id { get; set; }
        public decimal uid { get; set; }
        public string order_id { get; set; }
        public long order_id_key { get; set; }
        public long total_num { get; set; }
        public decimal cid { get; set; }
        public decimal pid { get; set; }
        public long people { get; set; }
        public System.DateTime create_time { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public Nullable<System.DateTime> stop_time { get; set; }
        public decimal k_id { get; set; }
        public bool is_tpl { get; set; }
        public bool is_refund { get; set; }
        public bool status { get; set; }
        public Nullable<bool> is_del { get; set; }
        public string unique_id { get; set; }
    }
}
