//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class store_product_reply
    {
        public long id { get; set; }
        public long uid { get; set; }
        public long oid { get; set; }
        public string unique { get; set; }
        public long product_id { get; set; }
        public string reply_type { get; set; }
        public int product_score { get; set; }
        public int service_score { get; set; }
        public string comment { get; set; }
        public string pics { get; set; }
        public System.DateTime create_time { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public string merchant_reply_content { get; set; }
        public Nullable<System.DateTime> merchant_reply_time { get; set; }
        public bool is_del { get; set; }
        public bool is_reply { get; set; }
    }
}
