//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class store_product_attr_value
    {
        public decimal id { get; set; }
        public decimal product_id { get; set; }
        public string sku { get; set; }
        public long stock { get; set; }
        public Nullable<long> sales { get; set; }
        public string image { get; set; }
        public string unique { get; set; }
        public string bar_code { get; set; }
        public Nullable<decimal> ot_price { get; set; }
        public decimal weight { get; set; }
        public decimal volume { get; set; }
        public decimal brokerage { get; set; }
        public decimal brokerage_two { get; set; }
        public decimal pink_price { get; set; }
        public int pink_stock { get; set; }
        public decimal seckill_price { get; set; }
        public int seckill_stock { get; set; }
        public Nullable<long> integral { get; set; }
        public decimal price { get; set; }
        public decimal cost { get; set; }
    }
}
