//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class store_order_status
    {
        public decimal id { get; set; }
        public decimal oid { get; set; }
        public string change_type { get; set; }
        public string change_message { get; set; }
        public System.DateTime change_time { get; set; }
    }
}
