//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class store_product_rule
    {
        public int id { get; set; }
        public string rule_name { get; set; }
        public string rule_value { get; set; }
        [NotMapped]
        public Dictionary<string,object> rule_value_json {
            get
            {
                return JsonConvert.DeserializeObject<Dictionary<string, object>>(string.IsNullOrEmpty(rule_value) ? "{}" : rule_value);
            }
            set
            {
                rule_value = value.ToString();
            }
            }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public Nullable<bool> is_del { get; set; }
    }
}
