//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class store_bargain_user
    {
        public decimal id { get; set; }
        public Nullable<decimal> uid { get; set; }
        public Nullable<decimal> bargain_id { get; set; }
        public Nullable<decimal> bargain_price { get; set; }
        public bool status { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public bool is_del { get; set; }
    }
}
