//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class store_combination
    {
        public decimal id { get; set; }
        public decimal product_id { get; set; }
        public Nullable<long> mer_id { get; set; }
        public string image { get; set; }
        public string images { get; set; }
        public string title { get; set; }
        public string attr { get; set; }
        public long people { get; set; }
        public string info { get; set; }
        public Nullable<decimal> product_price { get; set; }
        public long sort { get; set; }
        public long sales { get; set; }
        public Nullable<long> stock { get; set; }
        public System.DateTime create_time { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public bool is_host { get; set; }
        public bool is_show { get; set; }
        public bool is_del { get; set; }
        public bool combination { get; set; }
        public Nullable<bool> mer_use { get; set; }
        public string description { get; set; }
        public System.DateTime start_time { get; set; }
        public System.DateTime stop_time { get; set; }
        public int effective_time { get; set; }
        public long cost { get; set; }
        public Nullable<int> browse { get; set; }
        public string unit_name { get; set; }
        public Nullable<bool> spec_type { get; set; }
        public Nullable<int> temp_id { get; set; }
    }
}
