//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class store_bargain
    {
        public decimal id { get; set; }
        public decimal product_id { get; set; }
        public string title { get; set; }
        public string image { get; set; }
        public string unit_name { get; set; }
        public Nullable<long> stock { get; set; }
        public Nullable<long> sales { get; set; }
        public string images { get; set; }
        public System.DateTime start_time { get; set; }
        public System.DateTime stop_time { get; set; }
        public string store_name { get; set; }
        public Nullable<long> num { get; set; }
        public long bargain_num { get; set; }
        public bool status { get; set; }
        public string description { get; set; }
        public string info { get; set; }
        public long sort { get; set; }
        public bool is_hot { get; set; }
        public bool is_del { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public bool is_postage { get; set; }
        public string rule { get; set; }
        public Nullable<long> look { get; set; }
        public Nullable<long> share { get; set; }
    }
}
