//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class store_coupon
    {
        public long id { get; set; }
        public string title { get; set; }
        public long integral { get; set; }
        public decimal coupon_price { get; set; }
        public decimal use_min_price { get; set; }
        public long coupon_time { get; set; }
        public long sort { get; set; }
        public bool status { get; set; }
        public string product_id { get; set; }
        public Nullable<sbyte> type { get; set; }
        public System.DateTime create_time { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public bool is_del { get; set; }
    }
}
