//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class system_store
    {
        public long id { get; set; }
        public string name { get; set; }
        public string introduction { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string detailed_address { get; set; }
        public string image { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string valid_time { get; set; }
        public string day_time { get; set; }
        public System.DateTime create_time { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public bool is_show { get; set; }
        public bool is_del { get; set; }
        public Nullable<System.DateTime> day_time_end { get; set; }
        public Nullable<System.DateTime> day_time_start { get; set; }
        public Nullable<System.DateTime> valid_time_end { get; set; }
        public Nullable<System.DateTime> valid_time_start { get; set; }
    }
}
