//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class system_store_staff
    {
        public long id { get; set; }
        public decimal uid { get; set; }
        public string nickname { get; set; }
        public string avatar { get; set; }
        public int store_id { get; set; }
        public string store_name { get; set; }
        public string staff_name { get; set; }
        public string phone { get; set; }
        public sbyte verify_status { get; set; }
        public Nullable<sbyte> status { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public Nullable<bool> is_del { get; set; }
    }
}
