//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class system_city
    {
        public int id { get; set; }
        public int city_id { get; set; }
        public int level { get; set; }
        public int parent_id { get; set; }
        public string area_code { get; set; }
        public string name { get; set; }
        public string merger_name { get; set; }
        public string lng { get; set; }
        public string lat { get; set; }
        public bool is_show { get; set; }
    }
}
