//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class system_user_task
    {
        public int id { get; set; }
        public string name { get; set; }
        public string real_name { get; set; }
        public string task_type { get; set; }
        public int number { get; set; }
        public int level_id { get; set; }
        public int sort { get; set; }
        public bool is_show { get; set; }
        public bool is_must { get; set; }
        public string illustrate { get; set; }
        public System.DateTime create_time { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public Nullable<bool> is_del { get; set; }
    }
}
