//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_extract
    {
        public decimal id { get; set; }
        public Nullable<decimal> uid { get; set; }
        public string real_name { get; set; }
        public string extract_type { get; set; }
        public string bank_code { get; set; }
        public string bank_address { get; set; }
        public string alipay_code { get; set; }
        public string mark { get; set; }
        public string fail_msg { get; set; }
        public Nullable<System.DateTime> fail_time { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public Nullable<sbyte> status { get; set; }
        public string wechat { get; set; }
        public Nullable<bool> is_del { get; set; }
    }
}
