//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_bill
    {
        public decimal id { get; set; }
        public decimal uid { get; set; }
        public string link_id { get; set; }
        public bool pm { get; set; }
        public string title { get; set; }
        public string category { get; set; }
        public string type { get; set; }
        public decimal number { get; set; }
        public decimal balance { get; set; }
        public string mark { get; set; }
        public System.DateTime create_time { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public bool status { get; set; }
        public Nullable<bool> is_del { get; set; }
    }
}
