//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_enter
    {
        public long id { get; set; }
        public long uid { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string district { get; set; }
        public string address { get; set; }
        public string merchant_name { get; set; }
        public string link_user { get; set; }
        public string link_tel { get; set; }
        public string charter { get; set; }
        public long add_time { get; set; }
        public long apply_time { get; set; }
        public int success_time { get; set; }
        public string fail_message { get; set; }
        public long fail_time { get; set; }
        public bool status { get; set; }
        public bool is_lock { get; set; }
        public bool is_del { get; set; }
    }
}
