//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_level
    {
        public int id { get; set; }
        public long uid { get; set; }
        public int level_id { get; set; }
        public int grade { get; set; }
        public int valid_time { get; set; }
        public bool is_forever { get; set; }
        public int mer_id { get; set; }
        public bool status { get; set; }
        public string mark { get; set; }
        public bool remind { get; set; }
        public bool is_del { get; set; }
        public System.DateTime create_time { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public int discount { get; set; }
    }
}
