//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class visits
    {
        public long id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string date { get; set; }
        public Nullable<long> ip_counts { get; set; }
        public Nullable<long> pv_counts { get; set; }
        public string week_day { get; set; }
    }
}
