//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class wechat_media
    {
        public long id { get; set; }
        public string type { get; set; }
        public string path { get; set; }
        public string media_id { get; set; }
        public string url { get; set; }
        public bool temporary { get; set; }
        public long add_time { get; set; }
    }
}
