//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class wechat_live
    {
        public long room_id { get; set; }
        public string name { get; set; }
        public string cover_imge { get; set; }
        public string share_imge { get; set; }
        public Nullable<int> live_status { get; set; }
        public Nullable<long> start_time { get; set; }
        public Nullable<long> end_time { get; set; }
        public string anchor_name { get; set; }
        public string anchor_wechat { get; set; }
        public string anchor_imge { get; set; }
        public Nullable<bool> type { get; set; }
        public Nullable<bool> screen_type { get; set; }
        public Nullable<bool> close_like { get; set; }
        public Nullable<bool> close_comment { get; set; }
        public Nullable<bool> close_goods { get; set; }
        public string product_id { get; set; }
        public Nullable<bool> close_replay { get; set; }
        public Nullable<bool> close_share { get; set; }
        public Nullable<bool> close_kf { get; set; }
    }
}
