//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper
{
    using System;
    using System.Collections.Generic;
    
    public partial class wechat_live_goods
    {
        public long goods_id { get; set; }
        public Nullable<long> product_id { get; set; }
        public string cover_imge_url { get; set; }
        public string url { get; set; }
        public string price_type { get; set; }
        public string price { get; set; }
        public string price2 { get; set; }
        public string name { get; set; }
        public string third_party_tag { get; set; }
        public Nullable<long> audit_id { get; set; }
        public Nullable<long> audit_status { get; set; }
    }
}
